use_frameworks!

target 'Cyhz_Component_Support_Example' do
  pod 'Cyhz_Component_Support', :path => '../'

  target 'Cyhz_Component_Support_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
